export const FETCHIGN_DATA = 'FETCHIGN_DATA';
export const FETCHIGN_DATA_SUCCESS = 'FETCHIGN_DATA_SUCCESS';
export const FETCHIGN_DATA_FAILURE = 'FETCHIGN_DATA_FAILURE';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_CANCEL = 'LOGIN_USER_CANCEL';
export const VALIDATING_USER = 'VALIDATING_USER';
export const VALIDATING_USER_SUCCESS = 'VALIDATING_USER_SUCCESS';
export const VALIDATING_USER_FAILURE = 'VALIDATING_USER_FAILURE';
export const LOGINOUT_USER = 'LOGINOUT_USER';
export const LOGINOUT_USER_SUCCESS = 'LOGINOUT_USER_SUCCESS';
export const SAVING_DATA_USER = 'SAVING_DATA_USER';
export const SAVING_DATA_USER_SUCCESS = 'SAVING_DATA_USER_SUCCESS';
export const SAVING_DATA_USER_FAILURE = 'SAVING_DATA_USER_FAILURE';
export const GETTIN_STORAGE_USER_DATA = 'GETTIN_STORAGE_USER_DATA';
export const GETTIN_STORAGE_USER_DATA_SUCCESS = 'GETTIN_STORAGE_USER_DATA_SUCCESS';
export const GETTIN_STORAGE_USER_DATA_FAILURE = 'GETTIN_STORAGE_USER_DATA_FAILURE';

export const GETTING_LOCATION = 'GETTING_LOCATION';
export const GETTING_LOCATION_SUCCESS = 'GETTING_LOCATION_SUCCESS';
export const GETTING_LOCATION_FAILURE = 'GETTING_LOCATION_FAILURE';

export const FETCHIGN_ALL_CENTERS = 'FETCHIGN_ALL_CENTERS';
export const FETCHIGN_ALL_CENTERS_SUCCESS = 'FETCHIGN_ALL_CENTERS_SUCCESS';
export const FETCHIGN_ALL_CENTERS_FAILURE = 'FETCHIGN_ALL_CENTERS_FAILURE';
export const GETTING_USER_DATA = 'GETTING_USER_DATA';
export const GETTING_USER_DATA_SUCCESS = 'GETTING_USER_DATA_SUCCESS';
export const GETTING_USER_DATA_FAILURE = 'GETTING_USER_DATA_FAILURE';
export const GETTING_CENTER_DATA = 'GETTING_CENTER_DATA';
export const GETTING_CENTER_DATA_SUCCESS = 'GETTING_CENTER_DATA_SUCCESS';
export const GETTING_CENTER_DATA_FAILURE = 'GETTING_CENTER_DATA_FAILURE';
export const GET_CENTER_DATA = 'GET_CENTER_DATA';

export const UPDATING_CENTER_DATA = 'UPDATING_CENTER_DATA';
export const UPDATING_CENTER_DATA_SUCCESS = 'UPDATING_CENTER_DATA_SUCCESS';
export const UPDATING_CENTER_DATA_FAILURE = 'UPDATING_CENTER_DATA_FAILURE';

export const GETTING_CENTER_STORAGE = 'GETTING_CENTER_STORAGE';
export const GETTING_CENTER_STORAGE_SUCCESS = 'GETTING_CENTER_STORAGE_SUCCESS';
export const GETTING_CENTER_STORAGE_FAILURE = 'GETTING_CENTER_STORAGE_FAILURE';

export const GETTING_STORES = 'GETTING_STORES';
export const GETTING_STORES_SUCCESS = 'GETTING_STORES_SUCCESS';
export const GETTING_STORES_FAILURE = 'GETTING_STORES_FAILURE';
export const GETTING_KEY_STORE = 'GETTING_KEY_STORE';
export const GETTING_KEY_STORE_SUCCESS = 'GETTING_KEY_STORE_SUCCESS';
export const GETTING_KEY_STORE_FAILURE = 'GETTING_KEY_STORE_FAILURE';
export const UPDATING_STORE = 'UPDATING_STORE';
export const UPDATING_STORE_SUCCESS = 'UPDATING_STORE_SUCCESS';
export const UPDATING_STORE_FAILURE = 'UPDATING_STORE_FAILURE';

export const UPDATING_FIELD_STORE = 'UPDATING_FIELD_STORE';
export const UPDATING_FIELD_STORE_SUCCESS = 'UPDATING_FIELD_STORE_SUCCESS';
export const UPDATING_FIELD_STORE_FAILURE = 'UPDATING_FIELD_STORE_FAILURE';

export const UPLOADING_FILE = 'UPLOADING_FILE';
export const UPLOADING_FILE_SUCCESS = 'UPLOADING_FILE_SUCCESS';
export const UPLOADING_FILE_FAILURE = 'UPLOADING_FILE_FAILURE';
export const UPLOADING_FILE_PROGRESS = 'UPLOADING_FILE_PROGRESS';

export const GETTING_PRODUCTS_STORE = 'GETTING_PRODUCTS_STORE';
export const GETTING_PRODUCTS_STORE_SUCCESS = 'GETTING_PRODUCTS_STORE_SUCCESS';
export const GETTING_PRODUCTS_STORE_ERROR = 'GETTING_PRODUCTS_STORE_ERROR';

export const GETTING_KEY_PRODUCT = 'GETTING_KEY_PRODUCT';
export const GETTING_KEY_PRODUCT_SUCCESS = 'GETTING_KEY_PRODUCT_SUCCESS';
export const GETTING_KEY_PRODUCT_ERROR = 'GETTING_KEY_PRODUCT_ERROR';

export const UPDATING_PRODUCT = 'UPDATING_PRODUCT';
export const UPDATING_PRODUCT_SUCCESS = 'UPDATING_PRODUCT_SUCCESS';
export const UPDATING_PRODUCT_ERROR = 'UPDATING_PRODUCT_ERROR';

export const UPDATING_PRODUCT_FIELD = 'UPDATING_PRODUCT_FIELD';
export const UPDATING_PRODUCT_FIELD_SUCCESS = 'UPDATING_PRODUCT_FIELD_SUCCESS';
export const UPDATING_PRODUCT_FIELD_ERROR = 'UPDATING_PRODUCT_FIELD_ERROR';
